name = "splashfood-backend"
main = "src/index.ts"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "splashfood-db"
database_id = "85326999-ba92-4e4a-ac53-5543f778aaf9"

[[r2_buckets]]
binding = "R2"
bucket_name = "splashfood-images"

[vars]
JWT_SECRET = "splashfood-super-secret-jwt-key-2026-change-in-prod"
R2_PUBLIC_URL = "https://pub-6ac384b9162e4591a6d31dbe706c6433.r2.dev"
FRONTEND_ORIGIN = "https://splash-food-menu.pages.dev"
DASHBOARD_ORIGIN = "https://splashfood-dashboard.pages.dev"
